name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Release
        uses: docker://softprops/action-gh-release:a178add808ad86f0833c5833a8328524184d73f8
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: Release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}