name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Release
        uses: docker://softprops/action-gh-release:a178add808ad86f0833c5833a8328524184d73f8
        with:
          files: "*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}